# Generated by Django 4.2.3 on 2023-07-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_code', models.IntegerField(unique=True)),
                ('branch_name', models.CharField(max_length=255)),
                ('account_title', models.CharField()),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.IntegerField(unique=True)),
                ('text_payer_id', models.CharField(max_length=255)),
            ],
        ),
    ]
