# Generated by Django 4.2.3 on 2023-07-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField(unique=True)),
                ('country', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
