# Generated by Django 4.2.3 on 2023-07-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0002_address_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address_detail',
            name='phone_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
