# Generated by Django 4.2.3 on 2023-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0003_alter_address_detail_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
