# Generated by Django 4.2.3 on 2023-07-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app10', '0005_alter_bank_bank_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
