# Generated by Django 4.2.3 on 2023-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_detail_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('emp_id', models.IntegerField(unique=True)),
                ('phone_no', models.IntegerField(unique=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'femail')], max_length=1)),
                ('birthday', models.DateField()),
                ('AboutMe', models.CharField(max_length=300)),
            ],
        ),
    ]
