# Generated by Django 4.2.3 on 2023-07-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_personal_detail_model_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_detail_model',
            name='emp_id',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='personal_detail_model',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'femail')]),
        ),
        migrations.AlterField(
            model_name='personal_detail_model',
            name='phone_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
