# Generated by Django 4.2.3 on 2023-07-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0003_alter_personal_detail_model_emp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Document', models.ImageField(upload_to='')),
            ],
        ),
    ]
