# Generated by Django 4.2.3 on 2023-07-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_document_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phonenumber', models.BigIntegerField(unique=True)),
                ('country', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
