# Generated by Django 4.2.3 on 2023-07-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmedialink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('social_meadia', models.URLField()),
            ],
        ),
    ]
