# Generated by Django 4.2.3 on 2023-07-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_socialmedialink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_model',
            name='Document',
            field=models.FileField(upload_to='document/'),
        ),
    ]
