# Generated by Django 4.2.3 on 2023-07-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0008_alter_document_model_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency_contact',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='personal_detail_model',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
