# Generated by Django 4.2.3 on 2023-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=100)),
                ('Parent_department', models.CharField(choices=[('Main Department', 'Main Department'), ('Admin$Hrm', 'Admin$Hrm'), ('Account', 'Account'), ('Development', 'Development'), ('Software', 'Software'), ('Ui&Ux', 'Ui&Ux')], max_length=150)),
                ('Location', models.CharField(max_length=100)),
                ('Work_Shift', models.CharField(choices=[('Regular work shift', 'Regular work shift'), ('demo working shift regular', 'demo working shift regular'), ('demo working shift scheduled', 'demo working shift scheduled')], max_length=150)),
                ('Description', models.TextField(max_length=150)),
            ],
        ),
    ]
