# Generated by Django 4.2.3 on 2023-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddepartment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
