# Generated by Django 4.2.3 on 2023-07-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_adddesignation_manager_alter_adddepartment_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddDesignation',
        ),
        migrations.AddField(
            model_name='adddepartment',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adddepartment',
            name='Parent_department',
            field=models.CharField(choices=[('Main Department', 'Main Department'), ('Admin $ HR', 'Admin $ HR'), ('Account', 'Account'), ('Development', 'Development'), ('Software', 'Software'), ('Ui&Ux', 'Ui&Ux')], max_length=150),
        ),
        migrations.AlterField(
            model_name='adddepartment',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
