# Generated by Django 4.2.3 on 2023-07-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_adddesignation_adddepartment_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddepartment',
            name='active',
        ),
        migrations.AddField(
            model_name='adddepartment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
