# Generated by Django 4.2.3 on 2023-07-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_adddepartment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddepartment',
            name='new_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
