# Generated by Django 4.2.3 on 2023-07-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_adddepartment_new_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adddepartment',
            old_name='new_active',
            new_name='in_active',
        ),
    ]
