# Generated by Django 4.2.3 on 2023-07-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_adddepartment_in_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('Description', models.TextField(max_length=150)),
                ('No_of_Employees', models.IntegerField(max_length=150)),
            ],
        ),
    ]
