# Generated by Django 4.2.3 on 2023-07-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_name_adddepartment_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('No_of_Employees', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adddepartment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='adddepartment',
            name='full_name',
        ),
        migrations.AddField(
            model_name='adddepartment',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
