# Generated by Django 4.2.3 on 2023-07-20 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_adddesignation_remove_adddepartment_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddepartment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
