# Generated by Django 4.2.3 on 2023-07-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_adddepartment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddepartment',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
