# Generated by Django 4.2.3 on 2023-07-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_adddepartment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddepartment',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
