# Generated by Django 4.2.3 on 2023-07-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_adddepartment_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddesignation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
