# Generated by Django 4.1.7 on 2023-07-19 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Start_date', models.DateTimeField()),
                ('End_date', models.DateTimeField()),
                ('shift_type', models.BooleanField(choices=[('Regular Work Shift', 'Regular Work Shift '), ('Demo working Shift regular', 'Demo working Shift regular'), ('demo working shift sheduled', 'Demo working shift sheduled')], default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('weekend_day', models.CharField(choices=[('Sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('Break_time', models.CharField(choices=[('Tea Break', 'Tea Break'), ('Lunch Break', 'Lunch Break')], max_length=20)),
                ('Description', models.TextField(blank=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.department')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.employee')),
            ],
        ),
    ]
