# Generated by Django 4.1.7 on 2023-07-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_work_shift_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_shift',
            name='shift_type',
            field=models.BooleanField(choices=[(True, 'Regular '), (False, 'Scheduled')], default=True),
        ),
    ]
