# Generated by Django 4.2.3 on 2023-07-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_work_shift_shift_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_shift',
            name='shift_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('sheduled', 'sheduled')], default=True, max_length=100),
        ),
    ]
