# Generated by Django 4.2.3 on 2023-07-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_alter_work_shift_shift_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('discription', models.TextField(blank=True)),
                ('No_of_Employee', models.CharField(max_length=100)),
            ],
        ),
    ]
